import Head from 'next/head'
import Drag from '../components/Drag'
import DragAndDrop from '../components/DragAndDrop';
import KanbanDragAndDrop from '../components/KanbanDragAndDrop';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
          {/* <Drag /> */}
          {/* <DragAndDrop /> */}
          <KanbanDragAndDrop/>
      </main>
    </div>
  )
}
